### ISSUE TITLE
`neo4j-cypher-dsl-codegen` not working with Kotlin classes

### ISSUE THREAD

**Issue by tlukawski** [neo4j-contrib/cypher-dsl#504] opened 2022-11-22 08:21 UTC
Hi,

I tried to use `neo4j-cypher-dsl-codegen` with a kotlin project and no classes are being generated.
Am I missing something, or Kotlin classes are not supported yet ?

**Comment by michael-simons** [comment] 2022-11-22 15:03
Hey Tomasz,

I am not a Kotlin expert, but the annotation processor works with Java during the annotation processing phase. 
I have no clue how the work is distributed between the Kotlin compiler and Javac or if the Kotlin compiler has similar hooks for Java annotation processors like Javac.

In short: IDK, if works, than by coincidence. Can you share a simple project (one class should be enough) and how you would set up annotation processing in Kotlin so that we can have a look?

**Comment by michael-simons** [comment] 2023-07-03 07:52
Closing due to no feedback. Please open this again with a small reproducer of some kind if needed. Thank you.

**Closed by michael-simons** 2023-07-03 07:52 UTC
